services:
  twitter-fixer:
    image: ghcr.io/mywill/discordurlfixer:latest
    container_name: twitter-fixer
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./server-config.json:/app/server-config.json
